export default {
    LOGIN: "LOGIN",
    SIGNUP:"SIGNUP",
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    GET_BALANCE: "ADD_BALANCE",
    ORDER_TRANSACTION:"ORDER_TRANSACTION",
    GET_TRANSACTION:"GET_TRANSACTION"
    
}