export default {
    LOGIN: "LOGIN",
    SIGNUP:"SIGNUP",
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    GET_BALANCE: "ADD_BALANCE",
    ORDER_TRANSACTION:"ORDER_TRANSACTION",
    GET_TRANSACTION:"GET_TRANSACTION",
    ACTIVATE_OFFER:"ACTIVATE_OFFER",
    UPDATE_COMMISSION:"UPDATE_COMMISSION",
    UPDATE_SLIDER_IMAGES:"UPDATE_SLIDER_IMAGES"
    
}